# Generated by Django 5.1 on 2024-09-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizquestion_t_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfile',
            name='quiz_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='quiz.quiztype'),
        ),
        migrations.AlterField(
            model_name='quiztype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
