# Generated by Django 5.1 on 2024-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizfile_quiz_type_alter_quiztype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
