# Generated by Django 5.1 on 2024-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizfile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizaccess',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=20),
        ),
    ]
